apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  labels:
    app: influxdb
spec:
  ports:
    - name: standard
      protocol: TCP
      port: 8086 
  selector:
    app: influxdb
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: influxdb-depl
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
     matchLabels:
       app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: my_influxdb
        imagePullPolicy: Never
        ports:
          - containerPort: 8086
        volumeMounts:
          - name: influxdb-pv
            mountPath: /var/lib/influxdb
          - name: influxdb-conf
            mountPath: /etc/influxdb/influxdb.conf
            subPath: influxdb.conf
            readOnly: true
      volumes:
      - name: influxdb-pv
        persistentVolumeClaim:
            claimName: influxdb-pvc
      - name: influxdb-conf
        configMap:
            name: influxdb-conf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-conf
  labels:
    app: influxdb
data:
  influxdb.conf: |
    bind-address = "127.0.0.1:8088"
    [meta]
      dir = "/var/lib/influxdb/meta"
    [data]
      dir = "/var/lib/influxdb/data"
      wal-dir = "/var/lib/influxdb/wal"
      trace-logging-enabled = true
    [http]
      bind-address = ":8086"
      log-enabled = true
    [[graphite]]
      database = "telegraf"
