apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  labels:
    app: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: metallb
spec:
  ports:
    - name: in
      protocol: TCP
      port: 3000 
  type: LoadBalancer
  selector:
    app: grafana 
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: grafana-depl
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
     matchLabels:
       app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: my_grafana
        imagePullPolicy: Never
        ports:
            - containerPort: 3000 
