apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: metallb
spec:
  ports:
    - port: 5000
      targetPort: 80
  selector:
    app: phpmyadmin
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: my_phpmyadmin:latest
        imagePullPolicy: Never
        name: phpmyadmin
        ports:
        - containerPort: 80
        volumeMounts:
            - name: phpmyadmin-conf 
              mountPath: /var/www/html/config.inc.php
              subPath: config.inc.php
              readOnly: true
      volumes:
      - name: phpmyadmin-conf
        configMap:
          name: phpmyadmin-conf

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phpmyadmin-conf
  labels:
    app: influxdb
data:
  config.inc.php: |
                <?php
                /* vim: set expandtab sw=4 ts=4 sts=4: */
                
                /**
                 * This is needed for cookie based authentication to encrypt password in
                 * cookie. Needs to be 32 chars long.
                 */
                $cfg['blowfish_secret'] = ')AR^&shca5J?mGaHjsEmsks79%#y>A^f'; /* YOU MUST FILL IN THIS FOR COOKIE AUTH! */
                
                /**
                 * Servers configuration
                 */
                $i = 0;
                
                /**
                 * First server
                 */
                $i++;
                /* Authentication type */
                $cfg['Servers'][$i]['auth_type'] = 'cookie';
                /* Server parameters */
                $cfg['Servers'][$i]['host'] = 'mysql-svc';
                $cfg['Servers'][$i]['port'] = '3306';
                $cfg['Servers'][$i]['user'] = 'root';
                $cfg['Servers'][$i]['password'] = 'admin';
                $cfg['Servers'][$i]['compress'] = false;
                $cfg['Servers'][$i]['AllowNoPassword'] = false;
                
                /**
                 * Directories for saving/loading files from server
                 */
                $cfg['UploadDir'] = '';
                $cfg['SaveDir'] = '';
