apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: metallb
spec:
  ports:
    - port: 5050 
      targetPort: 80
  selector:
    app: wordpress
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-depl
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: my_wordpress:latest
        imagePullPolicy: Never
        name: wordpress
        ports:
        - containerPort: 80
